import Image from "next/image";
import Footer from "@/components/Footer";
import DonacionForm from "@/components/DonacionForm";
import { ArrowDown, ArrowUpRight, BookOpen, Heart, Landmark, Laptop, Sprout } from "lucide-react";

const opciones = [
  { Icon: Laptop, titulo: "Equipa un sueño", descripcion: "Dona mobiliario y equipos.", detalle: "Un computador, un pupitre o un libro pueden abrir un mundo de posibilidades.", categoria: "Recursos que abren caminos", color: "bg-[#eef1f3]", iconColor: "bg-[#dce5eb] text-[#355267]" },
  { Icon: Heart, titulo: "Invierte en una vida", descripcion: "Apadrina un estudiante.", detalle: "Acompaña una historia y sé parte de su oportunidad de aprender y crecer.", categoria: "Personas que dejan huella", color: "bg-[#f5ede7]", iconColor: "bg-[#edddd2] text-[#89553e]" },
  { Icon: Sprout, titulo: "Haz crecer una oportunidad", descripcion: "Apoya nuestros programas sociales.", detalle: "Ayúdanos a llevar la educación y el acompañamiento a más historias de vida.", categoria: "Ideas que transforman", color: "bg-[#edf1e9]", iconColor: "bg-[#dce5d4] text-[#506343]" },
  { Icon: Landmark, titulo: "Construyamos el futuro", descripcion: "Apoya el desarrollo de nuestro objeto social.", detalle: "Suma tu aporte a los recursos y proyectos que hacen posible nuestra misión.", categoria: "Un propósito compartido", color: "bg-[#f4efdf]", iconColor: "bg-[#eae0bf] text-[#806321]" },
];

export default function Donativos() {
  return (
    <main className="min-h-screen bg-[#fbf9f4] text-[#06141b]">
      <section className="relative overflow-hidden bg-[#061c24] px-6 pb-20 pt-40 text-white md:pb-28 md:pt-48">
        <div aria-hidden="true" className="pointer-events-none absolute -left-64 top-12 h-[650px] w-[650px] rounded-full border border-white/5" />
        <div className="relative mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[1.1fr_0.9fr] lg:gap-20">
          <div><p className="mb-7 flex items-center gap-3 text-xs font-medium tracking-[0.15em] text-[#e5ad20]"><span className="h-px w-8 bg-[#e5ad20]" /> Juntos, hacemos posible más</p><h1 className="max-w-xl font-serif text-5xl leading-[1.08] tracking-tight md:text-6xl">Haz posible un <span className="italic text-[#e5ad20]">nuevo comienzo.</span></h1><p className="mt-7 font-serif text-xl text-white/85">Una oportunidad. Un estudiante. Un futuro.</p><p className="mt-6 max-w-lg text-sm leading-7 text-white/65">En Nuevos Comienzos College creemos que la educación puede cambiar una historia. Tu aporte puede convertirse en un computador, un pupitre, un libro, una oportunidad educativa, el acompañamiento de un estudiante o en recursos para desarrollar programas que transformen vidas.</p><a href="#formas-de-aportar" className="mt-9 inline-flex items-center gap-4 rounded-xl bg-[#e5ad20] px-6 py-4 text-sm font-semibold text-[#06141b] transition-colors hover:bg-[#f5c344] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#e5ad20]">Encuentra tu forma de aportar <ArrowDown size={17} aria-hidden="true" /></a></div>
          <div className="relative mx-auto w-full max-w-md lg:mt-8"><div className="relative aspect-[4/4.4] overflow-hidden rounded-t-[160px] rounded-b-3xl border border-white/15"><Image src="/img/gradua.webp" alt="Jóvenes celebrando su graduación" fill sizes="(min-width: 1024px) 450px, 90vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#06141b]/90 via-transparent to-transparent" /><div className="absolute inset-x-0 bottom-0 p-8"><BookOpen size={27} className="mb-4 text-[#e5ad20]" strokeWidth={1.5} aria-hidden="true" /><p className="max-w-xs font-serif text-3xl leading-tight">El futuro también<br />se construye contigo.</p></div></div><div className="absolute -left-3 top-10 flex items-center gap-3 rounded-2xl border border-[#e5ad20]/25 bg-[#f5eddb] px-5 py-4 text-[#74521e] shadow-xl sm:-left-6"><Heart size={20} strokeWidth={1.5} aria-hidden="true" /><span className="text-xs font-semibold leading-5">Pequeños aportes.<br />Nuevas posibilidades.</span></div></div>
        </div>
      </section>
      <section id="formas-de-aportar" className="mx-auto max-w-6xl scroll-mt-28 px-6 py-20 md:py-28">
        <div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-4 text-xs font-semibold tracking-wider text-[#9b6c12]">Cuatro formas de dejar huella</p><h2 className="font-serif text-4xl leading-tight md:text-5xl">Cada aporte tiene<br /><span className="italic text-[#9b6c12]">una historia por delante.</span></h2></div><p className="max-w-xs text-sm leading-7 text-slate-600">Elige la forma de sumarte que más conecta contigo. Tú puedes ser parte de ese comienzo.</p></div>
        <div className="grid gap-6 md:grid-cols-2 md:gap-8">{opciones.map(({ Icon, titulo, descripcion, detalle, categoria, color, iconColor }, index) => <article key={titulo} className={`group relative flex flex-col overflow-hidden rounded-[28px] border border-[#06141b]/5 p-8 transition-shadow duration-300 hover:shadow-xl hover:shadow-[#06141b]/5 sm:p-11 ${color}`}><div className="mb-8 flex items-center justify-between"><span className={`grid h-14 w-14 place-items-center rounded-2xl ${iconColor}`}><Icon size={26} strokeWidth={1.5} aria-hidden="true" /></span><span className="font-serif text-5xl text-[#06141b]/15" aria-hidden="true">0{index + 1}</span></div><p className="mb-3 text-xs font-medium tracking-wide text-slate-500">{categoria}</p><h3 className="font-serif text-3xl leading-tight">{titulo}</h3><p className="mt-4 font-medium leading-7">{descripcion}</p><p className="mt-2 max-w-sm text-sm leading-7 text-slate-600">{detalle}</p><div className="mt-auto pt-8"><DonacionForm modalidad={titulo} /></div></article>)}</div>
        <div className="mt-16 rounded-[28px] bg-[#0b242c] p-8 text-white md:p-12"><div className="flex flex-col justify-between gap-6 border-b border-white/15 pb-8 sm:flex-row sm:items-center"><p className="font-serif text-3xl">Un mismo propósito.<br /><span className="italic text-[#e5ad20]">Muchos nuevos comienzos.</span></p><ArrowUpRight size={36} strokeWidth={1} className="text-[#e5ad20]" aria-hidden="true" /></div><div className="grid gap-6 pt-8 text-sm text-white/80 md:grid-cols-3">{["Formar para la vida.", "Preparar para el trabajo.", "Desarrollar para el futuro."].map((text,i)=><p key={text} className="flex items-center gap-4"><span className="text-xs text-[#e5ad20]">0{i+1}</span>{text}</p>)}</div></div>
        <p className="mx-auto mt-8 max-w-lg text-center text-xs leading-6 text-slate-500">Por ahora, podemos coordinar tu aporte a través del formulario. Los pagos en línea estarán disponibles próximamente.</p>
      </section>
      <Footer />
    </main>
  );
}
